FROM mcr.microsoft.com/devcontainers/typescript-node:20-bookworm

# RUN \
#     sudo apt-get update && \
#     sudo apt-get install -y \
#     && apt-get autoremove -y \
#     && apt-get clean -y \
#     && rm -rf /var/lib/apt/lists/*

RUN npm install -g create-next-app
